on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: write

name: Build and Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Verify versions
        run: rustc --version && rustup --version && cargo --version

      - name: Authenticate to registry
        uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Release package
        run: cargo publish --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
